spring:
  profiles:
    active:
     - dev
---
spring:    
  application:
    name: microsevicecloud-config-liu-dev
  profiles: dev
---
spring:
  application:
    name: microsevicecloud-config-liu-test
  profiles: test
