spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev  
    application:
       name: microsevicecloud-config-liu-dev
---
spring:
  profiles: test
   application:
       name: microsevicecloud-config-liu-test

