spring:
   profiles:
     active:
       - dev
---
spring:
   profiles: dev  #dev
   application:
     name: microsevicecloud-config-liu-dev
---
spring:
   profiles: test #test
   application:
     name: microsevicecloud-config-liu-test

#must save as utf-8